language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
env:
  global:
  - PROJECT_NAME=hicstuff
  - GITHUB_REPO_NAME=koszullab/hicstuff
os:
- linux
install:
- pip install -Ur requirements.txt
- pip install pytest pylint pytest-pylint
- pip install pytest-cov codecov
- if [[ $PYVER == "3.4" ]]; then
    pip install typing requests;
  fi
- python setup.py install
script:
- pytest --pylint --pylint-error-types=EF --pylint-rcfile=.pylintrc --doctest-modules hicstuff
- pytest --cov=hicstuff
- |
  if [[ $TRAVIS_TAG ]]; then
    python setup.py sdist;
  fi

after_success:
  - codecov -t $CODECOV_TOKEN

tags: true
