language: python
env:
  global:
  - PROJECT_NAME=hicstuff
  - GITHUB_REPO_NAME=koszullab/hicstuff
matrix:
  include:
  - python: '3.5'
  - python: '3.6'
  - python: '3.7'
    dist: xenial
    sudo: true
os:
- linux
before_install:
- sudo apt-get install -y bowtie2
- wget https://github.com/samtools/samtools/releases/download/1.9/samtools-1.9.tar.bz2
- tar xavf samtools-1.9.tar.bz2 && cd samtools-1.9
- "./configure && make && sudo make install && cd .."
- git clone https://github.com/lh3/minimap2
- cd minimap2 && make && cd ..
- export PATH="$PATH:$PWD/minimap2/"
install:
- pip install -Ur requirements.txt
- pip install pytest pylint pytest-pylint
- pip install pytest-cov codecov
- pip install .[mappy]
script:
- pytest --pylint --pylint-error-types=EF --pylint-rcfile=.pylintrc --doctest-modules
  hicstuff
- pytest --cov=hicstuff
- |
  if [[ $TRAVIS_TAG ]]; then
    python setup.py sdist;
  fi
after_success:
- codecov
tags: true
deploy:
  provider: pypi
  user: baudrly
  password:
    secure: FRo0IHxatM+TNmXnENbrvvQRGmc04owOFQRvpsctIBhxaHl/4W2ywrscfCL+wB/EmztQ6KAF05ictPxmwA1bl62dhEhflKmrZZEQ2riNvqmF09v4QGGybNkT1JIDO3tLhYYwHssBlJj6srNvahNKj2NayY0UDNyh1/u1tkW/M9JPaB9mKtfywoXB2VteaZH9EDeoQZkWzc5M+SK/aSlPfqdERa0PZT8Hnp1CAH8YsXJNkY3Bvi3OwkitDCXiBlaRGazImlTyGAcysH/KpxNyT619ejCHoMmMSl3dQIGafsIAkS0E1aZtbZ03XfoeAQcAoDcZl4V+ZvRny5FIzXLshWWErJbxknEzu8Jg2515XniSeXCSHnNYlQRB6Ggfc9L91K3chRWhWLOvEMcosn5eIuBc/ErZavs3EaxMND09RhjUdKwss6WbRW2hbFxJzm72FKxB6eRaSC8cjMc/xiChzeobQzfD/DctNN22CyS2pr3VMCps40ynKA6gL/TROd3OqI6bWAoqLfcUyYgMc1Qcog6ZN5b4p2wMB/wg4NRGMXexDksZhRSO6ZVDRJUnR41I04Fzkf0y+ZgpSP5sE5X8yhMc6tteai/jtcRHjPKZOQCV/PotAPzQIDKm9fz0Dqtd/pFLmosfcEQYskRJwxWZPg3IzdfCefH+kmlHEXpofvc=
  distributions: "sdist bdist_wheel"