language: python

env:
  global:
  - PROJECT_NAME=hicstuff
  - GITHUB_REPO_NAME=koszullab/hicstuff

matrix:
  include:
    - python: "3.5"
    - python: "3.6"
    - python: "3.7"
      dist: xenial
      sudo: true
    
os:
- linux

before_install:
- sudo apt install bowtie2
- git clone https://github.com/lh3/minimap2
- cd minimap2 && make && cd ..
- export PATH="$PATH:minimap2/"
install:
- pip install -Ur requirements.txt
- pip install pytest pylint pytest-pylint
- pip install pytest-cov codecov
- python setup.py install
script:
- pytest --pylint --pylint-error-types=EF --pylint-rcfile=.pylintrc --doctest-modules hicstuff
- pytest --cov=hicstuff
- |
  if [[ $TRAVIS_TAG ]]; then
    python setup.py sdist;
  fi

after_success:
  - codecov

tags: true
