language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
env:
  global:
  - PROJECT_NAME=hicstuff
  - GITHUB_REPO_NAME=koszullab/hicstuff
os:
- linux
install:
- pip install -r requirements.txt
- pip install pytest pylint pytest-cov pytest-pylint codecov 
- if [[ $PYVER == "3.4" ]]; then
    pip install typing;
  fi
- python setup.py install
script:
- pytest --pylint --pylint-error-types=EF --doctest-modules hicstuff
- cd tests;pytest --cov=hicstuff
- |
  if [[ $TRAVIS_TAG ]]; then
    python setup.py sdist;
  fi
 
after_success:
- codecov -e $PYVER
tags: true
