name: base
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python >= 3.7
  - pip
  - bowtie2 
  - bwa 
  - minimap2
  - samtools
  - numpy
  - scipy
  - pandas >= 1.5.0
  - matplotlib >= 3.4.0
  - docopt
  - biopython
  - requests
  - scikit-learn
  - pysam
  - htslib
  - pyfastx
  - cooler
  - pairtools
