{% set version = "1.2.28" %}

package:
  name: hicstuff
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/h/hicstuff/hicstuff-{{ version }}.tar.gz
  sha256: a1813b149404a0e414cd60ff16911ac78671ce45eb4b72402c8628a7fd4f052d

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip

  run:
    - python
    - numpy
    - pandas
    - scipy
    - docopt
    - scikit-learn
    - pysam
    - requests
    - biopython

test:
  imports:
    - hicstuff 

about:
  home: https://github.com/koszullab/hicstuff
  license: GPL-3.0
  license_file: LICENSE
  license_family: GPL
  summary: 'Simple library/pipeline to generate and handle simple Hi-C data '
  dev_url: https://github.com/koszullab/hicstuff
  doc_url: https://hicstuff.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - cmdoret
    - baudrly

